version: '3'
services:

  mongo-server:
    container_name: mongodb
    image: mongo
    env_file:
      - docker.env
    ports:
      - 27017:27017
    volumes:
      - /Users/supertree/data/mongo:/data/db

  redis-server:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/supertree/data/redis:/data
      - /Users/supertree/data/redis/config/:/usr/local/etc/redis/redis.conf
